name: lint
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  RUSTFLAGS: "-Dwarnings"
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run format
        run: cargo fmt --check --all
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libavutil-dev libavformat-dev libavfilter-dev libavdevice-dev
          version: 1.0
      - name: Run clippy
        run: cargo clippy --all-targets --all-features
